# -*- coding: utf-8 -*-
"""bedrock_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1jAoMxJKLFLf-IMrMMgUtcjFXLqftjU
"""

import streamlit as st
import boto3
import json

# Page config
st.set_page_config(
    page_title="LLaMA 3 Chatbot",
    page_icon="🤖",
    layout="wide"
)

# Custom CSS
st.markdown("""
<style>
    .main {
        background-color: #0E1117;
        color: white;
    }

    .stTextInput > div > div > input {
        background-color: #262730;
        color: white;
        border-radius: 10px;
    }

    .stButton button {
        width: 100%;
        border-radius: 10px;
        height: 3em;
        background-color: #4CAF50;
        color: white;
        font-weight: bold;
    }

    .chat-user {
        background-color: #1E88E5;
        padding: 12px;
        border-radius: 15px;
        margin-bottom: 10px;
        color: white;
    }

    .chat-bot {
        background-color: #262730;
        padding: 12px;
        border-radius: 15px;
        margin-bottom: 10px;
        color: white;
    }

    .sidebar .sidebar-content {
        background-color: #111827;
    }

    h1 {
        text-align: center;
        color: #4CAF50;
    }
</style>
""", unsafe_allow_html=True)

# Title
st.title("🤖 LLaMA 3 Chatbot")
st.caption("Powered by AWS Bedrock")

# Session state
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

# Sidebar
with st.sidebar:
    st.header("⚙ AWS Configuration")

    aws_access_key = st.text_input(
        "AWS Access Key ID",
        type="password"
    )

    aws_secret_key = st.text_input(
        "AWS Secret Access Key",
        type="password"
    )

    region = st.selectbox(
        "AWS Region",
        ["us-east-1", "us-west-2", "eu-west-1"]
    )

    connect = st.button("🚀 Connect")

# Connect to Bedrock
if connect and aws_access_key and aws_secret_key:
    try:
        session = boto3.Session(
            aws_access_key_id=aws_access_key,
            aws_secret_access_key=aws_secret_key,
            region_name=region
        )

        bedrock = session.client("bedrock-runtime")

        st.session_state.bedrock_client = bedrock

        st.sidebar.success("Connected Successfully!")

    except Exception as e:
        st.sidebar.error(f"Connection Failed: {e}")

# Chat UI
if "bedrock_client" in st.session_state:

    col1, col2 = st.columns([8, 1])

    with col1:
        user_input = st.text_input(
            "Message",
            placeholder="Type your message...",
            label_visibility="collapsed"
        )

    with col2:
        send = st.button("Send")

    # Send message
    if send and user_input.strip():

        st.session_state.chat_history.append({
            "role": "user",
            "content": user_input
        })

        # Build prompt
        prompt = ""

        for turn in st.session_state.chat_history:
            if turn["role"] == "user":
                prompt += f"### User:\n{turn['content']}\n\n"
            else:
                prompt += f"### Assistant:\n{turn['content']}\n\n"

        body = {
            "prompt": prompt,
            "temperature": 0.7,
            "top_p": 0.9,
            "max_gen_len": 512
        }

        try:
            response = st.session_state.bedrock_client.invoke_model(
                modelId="meta.llama3-8b-instruct-v1:0",
                body=json.dumps(body),
                contentType="application/json",
                accept="application/json"
            )

            response_body = json.loads(
                response["body"].read()
            )

            output_text = response_body.get(
                "generation",
                "No response generated."
            )

            st.session_state.chat_history.append({
                "role": "assistant",
                "content": output_text
            })

        except Exception as e:
            st.error(f"Error: {e}")

    # Display conversation
    st.markdown("---")

    for turn in st.session_state.chat_history:

        if turn["role"] == "user":
            st.markdown(
                f"""
                <div class="chat-user">
                    <b>🧑 You:</b><br>{turn['content']}
                </div>
                """,
                unsafe_allow_html=True
            )

        else:
            st.markdown(
                f"""
                <div class="chat-bot">
                    <b>🤖 LLaMA 3:</b><br>{turn['content']}
                </div>
                """,
                unsafe_allow_html=True
            )

else:
    st.info("Enter AWS credentials in the sidebar and connect to Bedrock.")